### ISSUE TITLE
get_field() is ACF function

### ISSUE THREAD

**Issue by jmfurlott** [jmfurlott/wp-api-yoast#1]
Remove get_field() such that it works without ACF

**Comment by seyDoggy** [comment]
I'm messing around with this and I'm not entirely sure why it doesn't work without ACF on the page? I always get `meta: null`

**Comment by jmfurlott** [comment]
I don't really remember that well, but I think I made this issue because `get_field` is from ACF and the plugin should be using a WP only function

**Comment by seyDoggy** [comment]
See PR #2

**Comment by jmfurlott** [comment]
Closed from PR #2
