### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by christianesperar** [jmfurlott/wp-api-yoast#3]
It seems this is not showing in the list of plugin

**Comment by jmfurlott** [comment]
@christianesperar haven't looked at anything WP in a while, but do you have support for other WP API plugins? Did you add support for WP itself

**Comment by christianesperar** [comment]
What do you mean? Is this plugin will just need to move on plugin folder and it will work as expected? I will try to modify it and I will send you a pull request.

**Comment by christianesperar** [comment]
False alarm. It's just my permission :P Thanks for this awesome plugin :+1:
